# Generated by Django 4.2.7 on 2024-01-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='each_products',
        ),
        migrations.AddField(
            model_name='order',
            name='each_products',
            field=models.ManyToManyField(related_name='orders', to='order.each_product'),
        ),
    ]
